#!/usr/bin/env python3
"""
Create demo PDF files for testing the PDF Merger app
"""

try:
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.colors import blue, red, green
    import os
    
    def create_demo_pdf(filename, title, content_lines, color):
        """Create a demo PDF with custom content"""
        c = canvas.Canvas(filename, pagesize=letter)
        width, height = letter
        
        # Set font and color
        c.setFont("Helvetica-Bold", 24)
        c.setFillColor(color)
        c.drawString(100, height - 100, title)
        
        # Add content
        c.setFont("Helvetica", 12)
        c.setFillColor(blue)
        y_position = height - 150
        
        for line in content_lines:
            c.drawString(100, y_position, line)
            y_position -= 25
        
        # Add footer
        c.setFont("Helvetica-Oblique", 10)
        c.setFillColor(red)
        c.drawString(100, 50, "Generated by PDF Merger Demo")
        
        c.save()
        print(f"Created demo PDF: {filename}")
    
    # Create demo PDFs
    print("Creating demo PDF files...")
    
    create_demo_pdf(
        "demo1.pdf",
        "Document 1: Introduction",
        [
            "This is the first document in our demo.",
            "It contains basic information about PDF merging.",
            "You can merge this with other PDFs to create a combined document.",
            "The PDF Merger app makes this process simple and efficient."
        ],
        blue
    )
    
    create_demo_pdf(
        "demo2.pdf", 
        "Document 2: Features",
        [
            "This document highlights the key features:",
            "• Drag and drop file upload",
            "• Real-time file validation", 
            "• Secure local processing",
            "• Beautiful modern UI",
            "• Mobile-friendly design"
        ],
        green
    )
    
    create_demo_pdf(
        "demo3.pdf",
        "Document 3: Instructions", 
        [
            "How to use the PDF Merger:",
            "1. Select multiple PDF files",
            "2. Review the file list",
            "3. Click 'Merge PDFs' button",
            "4. Download the merged document",
            "",
            "That's it! Your PDFs are now merged."
        ],
        red
    )
    
    print("\n✅ Demo PDF files created successfully!")
    print("You can now test the PDF Merger app with these files.")
    
except ImportError:
    print("❌ ReportLab library not found.")
    print("Please install it with: pip install reportlab")
    print("Or use the run_app.bat/run_app.sh scripts to install all dependencies.")
